sudo: true
os:
- linux
language: python
python:
- 3.6
addons:
  apt:
    packages:
    - libelf-dev
    - libdw-dev
    - binutils-dev
install:
- ./install_ta-lib.sh
- export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
- pip install --upgrade flake8 coveralls
- pip install -r requirements.txt
- pip install -e .
jobs:
  include:
    - script: pytest --cov=freqtrade --cov-config=.coveragerc freqtrade/tests/
    - script:
      - cp config.json.example config.json
      - python freqtrade/main.py backtesting
    - script:
      - cp config.binance.json.example config.json
      - python freqtrade/main.py backtesting
    - script:
      - cp config.json.example config.json
      - python freqtrade/main.py hyperopt -e 5
    - script:
      - cp config.binance.json.example config.json
      - python freqtrade/main.py hyperopt -e 5
    - script: flake8 freqtrade
after_success:
- coveralls
cache:
  directories:
    - $HOME/.cache/pip
    - ta-lib